services:
  mysql:
    image: mysql:8.4
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # rootユーザーのパスワード
      MYSQL_DATABASE: muscle             # 最初に作るデータベース名
      MYSQL_USER: user                   # 普通ユーザー名
      MYSQL_PASSWORD: userpassword       # 普通ユーザーのパスワード
    ports:
      - "3306:3306"                      # ホストの3306をコンテナの3306に割り当て
    volumes:
      - mysql_data:/var/lib/mysql        # データを永続化するディレクトリを指定

volumes:
  mysql_data:                            # Dockerが自動的に作成する外部保存領域（名前付きボリューム）
